name: Anirecs Workflow

on: push  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Check out repository code

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  
        
    - name: Install Poetry
      run: |
        pip install poetry
      working-directory: ./backend

    - name: Install dependencies
      run: |
        poetry install
      working-directory: ./backend  

    - name: Run flake8
      run: |
        poetry run flake8
      working-directory: ./backend  

    - name: Run Bandit
      run: |
        poetry run bandit -r .
      working-directory: ./backend  

    - name: Set up PostgreSQL Docker container
      run: |
        docker run --name test-postgres -e POSTGRES_DB=testdb -e POSTGRES_USER=user -e POSTGRES_PASSWORD=password -p 5432:5432 -d postgres
      working-directory: ./backend

    - name: Set environment variables
      run: |
        echo "TESTING=true" >> $GITHUB_ENV
        echo "TEST_DATABASE_URL=postgresql://user:password@test-postgres:5432/testdb" >> $GITHUB_ENV
      working-directory: ./backend

    - name: Run pytest
      run: |
        poetry run pytest --cov=anirecs --cov-branch --cov-report=term --cov-fail-under=60 
      working-directory: ./backend
